# File containing the input data. The columns are 'id' (name of the
# object), 'redshift' (if 0 the distance is assumed to be 10 pc),
# 'distance' (Mpc, optional, if present it will be used in lieu of the
# distance computed from the redshift), the filter (for instance FUV) or
# line names (prefixed with 'line.' for the latter, for instance
# line.H-alpha) for the fluxes, and the names of the physical properties
# as computed by the code (e.g. dust.luminosity). The uncertainties are
# given with the same column names with the '_err' suffix. The fluxes
# and the uncertainties must be in mJy for broadband data, in W/m² for
# emission lines, and the unit computed by the code for the physical
# proerties. Fluxes can be positive or negative. Upper limits are
# indicated with a negative value for the uncertainty. In case some
# fluxes are missing for some entries, they can be replaced with NaN.
# This file is optional to generate the configuration file, in
# particular for the savefluxes module.
data_file = gc_splus_cigale_custom.txt

# Optional file containing the list of physical parameters. Each column
# must be in the form module_name.parameter_name, with each line being a
# different model. The columns must be in the order the modules will be
# called. The redshift column must be the last one. Finally, if this
# parameter is not empty, cigale will not interpret the configuration
# parameters given in pcigale.ini. They will be given only for
# information. Note that this module should only be used in conjonction
# with the savefluxes module. Using it with the pdf_analysis module will
# yield incorrect results.
parameters_file = 

# Available modules to compute the models. The order must be kept.
# SFH:
# * sfh2exp (double exponential)
# * sfhdelayed (delayed SFH with optional exponential burst)
# * sfhdelayedbq (delayed SFH with optional constant burst/quench)
# * sfhfromfile (arbitrary SFH read from an input file)
# * sfhperiodic (periodic SFH, exponential, rectangle or delayed)
# SSP:
# * bc03 (Bruzual and Charlot 2003)
# * m2005 (Maraston 2005; note that it cannot be combined with the nebular module)
# Nebular emission:
# * nebular (continuum and line nebular emission)
# Dust attenuation:
# * dustatt_modified_CF00 (modified Charlot & Fall 2000 attenuation law)
# * dustatt_modified_starburst (modified Calzetti 2000 attenuaton law)
# Dust emission:
# * casey2012 (Casey 2012 dust emission models)
# * dale2014 (Dale et al. 2014 dust emission templates)
# * dl2007 (Draine & Li 2007 dust emission models)
# * dl2014 (Draine et al. 2014 update of the previous models)
# * themis (Themis dust emission models from Jones et al. 2017)
# AGN:
# * skirtor2016 (AGN models from Stalevski et al. 2012, 2016)
# * fritz2006 (AGN models from Fritz et al. 2006)
# X-ray:
# * xray (from AGN and galaxies; skirtor2016/fritz2006 is needed for AGN)
# Radio:
# * radio (galaxy synchrotron emission and AGN; skirtor2016/fritz2006 is needed for AGN)
# Restframe parameters:
# * restframe_parameters (UV slope (β), IRX, D4000, EW, etc.)
# Redshift+IGM:
# * redshifting (mandatory, also includes the IGM from Meiksin 2006)
sed_modules = sfhdelayed, bc03, redshifting

# Method used for statistical analysis. Available methods: pdf_analysis,
# savefluxes.
analysis_method = pdf_analysis

# Number of CPU cores available. This computer has 8 cores.
cores = 4

# Bands and emission lines to consider. To take uncertainties into
# account, the name of the band or line must be indicated with the _err
# suffix as in the input flux file. For instance: galex.FUV,
# galex.FUV_err. The list of allowed bands and lines can be obtained
# with pcigale-filters list. Line names must be prefixed with 'line.',
# for instance line.H-alpha, as in the input flux file.
bands = ,

# Properties to be considered. All properties are to be given in the
# rest frame rather than the observed frame. This is the case for
# instance the equivalent widths and for luminosity densities. The names
# correspond to those used in the input file with the uncertainties
# indicated with the _err suffix.
properties = ,

# Relative error added in quadrature to the uncertainties of the fluxes
# and the extensive properties. Uncertainties on intensive properties
# are left unchanged.
additionalerror = 0.1


# Configuration of the SED creation modules.
[sed_modules_params]
  
  [[sfhdelayed]]
    # e-folding time of the main stellar population model in Myr.
    tau_main = 2000.0
    # Age of the main stellar population in the galaxy in Myr. The precision
    # is 1 Myr.
    age_main = 5000
    # e-folding time of the late starburst population model in Myr.
    tau_burst = 50.0
    # Age of the late burst in Myr. The precision is 1 Myr.
    age_burst = 20
    # Mass fraction of the late burst population.
    f_burst = 0.0
    # Multiplicative factor controlling the SFR if normalise is False. For
    # instance without any burst: SFR(t)=sfr_A×t×exp(-t/τ)/τ²
    sfr_A = 1.0
    # Normalise the SFH to produce one solar mass.
    normalise = True
  
  [[bc03]]
    # Initial mass function: 0 (Salpeter) or 1 (Chabrier).
    imf = 0
    # Metallicity of the stellar populations. Possible values are: 0.0001,
    # 0.0004, 0.004, 0.008, 0.02, 0.05.
    metallicity = 0.02
    # Age [Myr] of the separation between the young and the old star
    # populations. The default value in 10^7 years (10 Myr). Set to 0 not to
    # differentiate ages (only an old population).
    separation_age = 10
  
  [[redshifting]]
    # Redshift of the objects. Leave empty to use the redshifts from the
    # input file.
    redshift = 


# Configuration of the statistical analysis method.
[analysis_params]
  # List of the physical properties to analyse. The analysis can be done
  # on the log of the value appending _log. To accelerate the computation,
  # properties of no interest to the study should be removed. Note: they
  # will still be provided for the best fit.
  variables = sfh.age, sfh.age_burst, sfh.age_main, sfh.f_burst, sfh.integrated, sfh.sfr, sfh.sfr100Myrs, sfh.sfr10Myrs, sfh.tau_burst, sfh.tau_main, stellar.age_m_star, stellar.imf, stellar.lum, stellar.lum_ly, stellar.lum_ly_old, stellar.lum_ly_young, stellar.lum_old, stellar.lum_young, stellar.m_gas, stellar.m_gas_old, stellar.m_gas_young, stellar.m_star, stellar.m_star_old, stellar.m_star_young, stellar.metallicity, stellar.n_ly, stellar.n_ly_old, stellar.n_ly_young, stellar.old_young_separation_age, universe.age, universe.luminosity_distance, universe.redshift
  # List of bands for which to estimate the fluxes. Note that this is
  # independent from the fluxes actually fitted to estimate the physical
  # properties.
  bands = ,
  # If true, save the best SED for each observation to a file.
  save_best_sed = False
  # Save the raw chi2. It occupies ~15 MB/million models/variable. Allowed
  # values are 'all', 'none', 'properties', and 'fluxes'.
  save_chi2 = none
  # Take into account upper limits. If 'full', the exact computation is
  # done. If 'noscaling', the scaling of the models will not be adjusted
  # but the χ² will include the upper limits adequately. Waiving the
  # adjustment makes the fitting much faster compared to the 'full' option
  # while generally not affecting the results in any substantial manner.
  # This is the recommended option as it achieves a good balance between
  # speed and reliability. Finally, 'none' simply discards bands with
  # upper limits.
  lim_flag = noscaling
  # If true, for each object we create a mock object and analyse them.
  mock_flag = False
  # When redshifts are not given explicitly in the redshifting module,
  # number of decimals to round the observed redshifts to compute the grid
  # of models. To disable rounding give a negative value. Do not round if
  # you use narrow-band filters.
  redshift_decimals = 2
  # Number of blocks to compute the models and analyse the observations.
  # If there is enough memory, we strongly recommend this to be set to 1.
  blocks = 1
